# See https://fly.io/docs/reference/configuration/

app = "my-litefs-app"
primary_region = "iad"

[build]
  # Uses Dockerfile by default

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = false
  min_machines_running = 1
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256

[mounts]
  source = "litefs"
  destination = "/var/lib/litefs"
